# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from plot_app import Ui_Plot_Window

def _LOGGER__(str__, type__ = ""):
    print("LOG:" + type__ + " " + str__)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 54))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_MainHeader = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(30)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Label_MainHeader.setFont(font)
        self.Label_MainHeader.setObjectName("Label_MainHeader")
        self.verticalLayout.addWidget(self.Label_MainHeader)
        self.PushB_plot_Y = QtWidgets.QPushButton(self.centralwidget)
        self.PushB_plot_Y.setGeometry(QtCore.QRect(400, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        self.PushB_plot_Y.setFont(font)
        self.PushB_plot_Y.setObjectName("PushB_plot_Y")
        self.PushB_clear_Y = QtWidgets.QPushButton(self.centralwidget)
        self.PushB_clear_Y.setGeometry(QtCore.QRect(600, 490, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.PushB_clear_Y.setFont(font)
        self.PushB_clear_Y.setObjectName("PushB_clear_Y")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(179, 59, 601, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.PlainT_data_X = QtWidgets.QTextEdit(self.frame)
        self.PlainT_data_X.setGeometry(QtCore.QRect(10, 10, 261, 411))
        self.PlainT_data_X.setObjectName("PlainT_data_X")
        self.PlainT_data_Y = QtWidgets.QTextEdit(self.frame)
        self.PlainT_data_Y.setGeometry(QtCore.QRect(330, 10, 261, 411))
        self.PlainT_data_Y.setObjectName("PlainT_data_Y")
        self.PushB_plot_FromFile = QtWidgets.QPushButton(self.centralwidget)
        self.PushB_plot_FromFile.setGeometry(QtCore.QRect(20, 260, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.PushB_plot_FromFile.setFont(font)
        self.PushB_plot_FromFile.setObjectName("PushB_plot_FromFile")
        self.PushB_clear_X = QtWidgets.QPushButton(self.centralwidget)
        self.PushB_clear_X.setGeometry(QtCore.QRect(270, 490, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.PushB_clear_X.setFont(font)
        self.PushB_clear_X.setObjectName("PushB_clear_X")
        self.PushB_plot_XY = QtWidgets.QPushButton(self.centralwidget)
        self.PushB_plot_XY.setGeometry(QtCore.QRect(490, 520, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        self.PushB_plot_XY.setFont(font)
        self.PushB_plot_XY.setObjectName("PushB_plot_XY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ######################################################
                        # New Code #
        ###################################################### 

        ## Plot widget object
        self.plotter_Window = QtWidgets.QWidget()
        self.plot_UI_Obj = Ui_Plot_Window()
        self.plot_UI_Obj.setupUi(self.plotter_Window)
        self.plot_UI_Obj.connect_Controls()

        ## File Explorer dialog box
        self.file_Explorer_Window =  QtWidgets.QFileDialog()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_MainHeader.setText(_translate("MainWindow", "                              PYQTGRAPH PLOTTING UTILITY - GUI"))
        self.PushB_plot_Y.setText(_translate("MainWindow", "Plot Y"))
        self.PushB_clear_Y.setText(_translate("MainWindow", "Clear"))
        self.PushB_plot_FromFile.setText(_translate("MainWindow", "Plot Data File"))
        self.PushB_clear_X.setText(_translate("MainWindow", "Clear"))
        self.PushB_plot_XY.setText(_translate("MainWindow", "Plot XY"))


    ######################################################
                    # New Code #
    ###################################################### 

    def connect_Controls(self):
        self.PushB_plot_FromFile.clicked.connect(self.read_DataFromFile_Handler)
        self.PushB_clear_X.clicked.connect(self.clear_TextData_X)
        self.PushB_clear_Y.clicked.connect(self.clear_TextData_Y)
        self.PushB_plot_Y.clicked.connect(self.plot_DataY)
        self.PushB_plot_XY.clicked.connect(self.plot_DataXY)

    def read_DataFromFile_Handler(self):
        try:
            data_file_path = self.file_Explorer_Window.getOpenFileName()
            print(data_file_path)
        except Exception as e:
            _LOGGER__("File open error" + e)
            pass

        self.plotter_Window.show()

    def clear_TextData_X(self):
        self.PlainT_data_X.clear()

    def clear_TextData_Y(self):
        self.PlainT_data_Y.clear()

    def plot_DataY(self):

        # Take data from IP
        raw_ip_Data_X = self.PlainT_data_X.toPlainText()
        proc_IP_Data_X = self.preProcess_IP_Data(raw_ip_Data_X)
        print(proc_IP_Data_X)
        self.plot_UI_Obj.curve_1.setData(proc_IP_Data_X)
        new_list_1 = [i * 3.12 for i in proc_IP_Data_X]
        new_list_2 = [i * 2.82 for i in proc_IP_Data_X]
        new_list_3 = [i * 7.92 for i in proc_IP_Data_X]
        self.plot_UI_Obj.curve_2.setData(new_list_1)
        self.plot_UI_Obj.curve_3.setData(new_list_2)
        self.plot_UI_Obj.curve_4.setData(new_list_3)

        # show plot window
        self.plotter_Window.show()

    def plot_DataXY(self):
        self.plotter_Window.show()

    ######################################################
                    # Utility Code #
    ###################################################### 

    def preProcess_IP_Data(self, raw_Data):
        op_Proc_Data = []
        try:
            str_Data_Lines = raw_Data.splitlines()
            for rdata in str_Data_Lines:
                if rdata == "":
                    continue
                else:
                    op_Proc_Data.append(float(rdata))
        except Exception as e:
            _LOGGER__("Error parsing IP Data" + e)
        return op_Proc_Data

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    m_ui = Ui_MainWindow()
    m_ui.setupUi(main_window)
    m_ui.connect_Controls()
    main_window.show()
    sys.exit(app.exec_())

