# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyqtgraph as pg

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plot_Window(object):
    def setupUi(self, Plot_Window):
        Plot_Window.setObjectName("Plot_Window")
        Plot_Window.resize(1250, 625)
        self.graphicsView = pg.PlotWidget(Plot_Window)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 1231, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Plot_Window)
        self.label.setGeometry(QtCore.QRect(510, 10, 221, 41))
        self.label.setObjectName("label")

        self.retranslateUi(Plot_Window)
        QtCore.QMetaObject.connectSlotsByName(Plot_Window)

    def retranslateUi(self, Plot_Window):
        _translate = QtCore.QCoreApplication.translate
        Plot_Window.setWindowTitle(_translate("Plot_Window", "Form"))
        self.label.setText(_translate("Plot_Window", "                     PYQTGRAPH PLOT"))

    def connect_Controls(self):
        pass