# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyqtgraph as pg

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plot_Window(object):
    def setupUi(self, Plot_Window):
        Plot_Window.setObjectName("Plot_Window")
        Plot_Window.resize(1250, 625)
        self.graphicsView = pg.PlotWidget(Plot_Window)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 1231, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.enableAutoRange()

        # 1st Yaxis
        self.graphicsView_YAxis_1 = self.graphicsView.getAxis('left')
        self.graphicsView_YAxis_1.setPen(pg.mkPen(color='#ff0000', width=3))

        # 2nd Yaxis
        self.graphicsView_YAxis_2_VBox = pg.ViewBox()
        self.graphicsView_YAxis_2 = pg.AxisItem('left')
        self.graphicsView.plotItem.layout.addItem(self.graphicsView_YAxis_2, -1, -3)
        self.graphicsView.scene().addItem(self.graphicsView_YAxis_2_VBox)
        self.graphicsView_YAxis_2.linkToView(self.graphicsView_YAxis_2_VBox)
        self.graphicsView_YAxis_2.setPen(pg.mkPen(color='#0000ff', width=3))

        self.label = QtWidgets.QLabel(Plot_Window)
        self.label.setGeometry(QtCore.QRect(510, 10, 221, 41))
        self.label.setObjectName("label")

        self.retranslateUi(Plot_Window)
        QtCore.QMetaObject.connectSlotsByName(Plot_Window)

    def retranslateUi(self, Plot_Window):
        _translate = QtCore.QCoreApplication.translate
        Plot_Window.setWindowTitle(_translate("Plot_Window", "Form"))
        self.label.setText(_translate("Plot_Window", "                     PYQTGRAPH PLOT"))

    def connect_Controls(self):
        pass

    ######################################################
                    # New Code #
    ###################################################### 

